# Machine Learning & PyTorch Basic

### 1. Numpy Review

In [1]:
import numpy as np
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [2]:
print('Rank of t :', t.ndim)
print('shape of t :', t.shape)

Rank of t : 1
shape of t : (7,)


In [3]:
print('t[0] t[1] t[-1] =', t[0], t[1], t[-1])
print('t[2:5] t[4:-1]  =', t[2:5], t[4:-1])
print('t[:2] t[3:]     =', t[:2], t[3:])

t[0] t[1] t[-1] = 0.0 1.0 6.0
t[2:5] t[4:-1]  = [2. 3. 4.] [4. 5.]
t[:2] t[3:]     = [0. 1.] [3. 4. 5. 6.]


In [4]:
t = np.array([[1., 2., 3.],
              [4., 5., 6.],
              [7., 8., 9.],
              [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [5]:
print('Rank of t :', t.ndim)
print('shape of t :', t.shape)

Rank of t : 2
shape of t : (4, 3)


### 2. PyTorch Tensor

In [6]:
import torch
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [7]:
print(t.dim())
print(t.shape)
print(t.size())
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [8]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [9]:
print(t.dim())
print(t.size())
print(t[:,-1])
print(t[:,1].size())
print(t[:, :-1])

2
torch.Size([4, 3])
tensor([ 3.,  6.,  9., 12.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


### Broadcasting

In [10]:
m1 = torch.FloatTensor([3,3])
m2 = torch.FloatTensor([2,2])
print(m1 + m2)

tensor([5., 5.])


In [11]:
m1 = torch.FloatTensor([1,2])
m2 = torch.FloatTensor([3])
print(m1 + m2)

tensor([4., 5.])


In [12]:
m1 = torch.FloatTensor([1,2])
m2 = torch.FloatTensor([[3],[4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


### Multiplication vs Matrix Multiplication

In [13]:
print()
print('='*20)
print('Mul vs Matmul')
print('='*20)

m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1],[2]])
print('shape of Matrix 1 : ', m1.shape)
print('shape of Matrix 2 : ', m2.shape)
print(m1.matmul(m2))

m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1],[2]])
print('shape of Matrix 1 : ', m1.shape)
print('shape of Matrix 2 : ', m2.shape)
print(m1 * m2)
print(m1.mul(m2))


Mul vs Matmul
shape of Matrix 1 :  torch.Size([2, 2])
shape of Matrix 2 :  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
shape of Matrix 1 :  torch.Size([2, 2])
shape of Matrix 2 :  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


### Mean

In [14]:
t = torch.FloatTensor([1., 2.])
print(t.mean())

tensor(1.5000)


In [15]:
t = torch.LongTensor([1, 2])

try : 
    print(t.mean())
except Exception as exc : 
    print(exc)

Can only calculate the mean of floating types. Got Long instead.


In [16]:
t = torch.FloatTensor([[1,2], [3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [17]:
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


### Sum

In [18]:
t = torch.FloatTensor([[1,2], [3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [19]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


### Max and Argmax

In [20]:
t = torch.FloatTensor([[1,2], [3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [21]:
print(t.max())

tensor(4.)


In [22]:
print(t.max(dim=0))
print('Max :', t.max(dim=0)[0])
print('Argmax :', t.max(dim=0)[1])

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max : tensor([3., 4.])
Argmax : tensor([1, 1])


In [23]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


### View(Reshape)

In [24]:
t = np.array([[[0,1,2],
               [3,4,5]],
                
              [[6,7,8],
               [9,10,11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [25]:
print(ft.view([-1,3]))
print(ft.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [26]:
print(ft.view([-1,1,3]))
print(ft.view([-1,1,3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


### Squeeze

In [27]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [28]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


### Unsqueeze

In [29]:
ft = torch.Tensor([0,1,2])
print(ft.shape)

torch.Size([3])


In [30]:
print(ft.unsqueeze(dim=0))
print(ft.unsqueeze(dim=0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [31]:
print(ft.view([1,-1]))
print(ft.view([1,-1]).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [32]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [33]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


### Type Casting

In [34]:
lt = torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [35]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [36]:
bt = torch.ByteTensor([True,True,False,True])
print(bt)

tensor([1, 1, 0, 1], dtype=torch.uint8)


In [37]:
print(bt.long())
print(bt.float())

tensor([1, 1, 0, 1])
tensor([1., 1., 0., 1.])


### Concatenate

In [38]:
x = torch.FloatTensor([[1,2],[3,4]])
y = torch.FloatTensor([[5,6],[7,8]])
print(torch.cat([x,y], dim=0))
print(torch.cat([x,y], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


### Stacking

In [39]:
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

In [40]:
print(torch.stack([x,y,z]))
print(torch.stack([x,y,z], dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [41]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


### Onez and Zeros

In [42]:
x = torch.FloatTensor([[0,1,2], [2,1,0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [43]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


### In-place Operation

In [44]:
x = torch.FloatTensor([[1,2], [3,4]])

In [45]:
print(x.mul(2.))
print(x)
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


### Linear Regression

$y = H(x) = Wx + b$

$cost(W,b) = {1 \over m} \sum_{i=1}^{m} (H(x^{(i)}) - y^{(i)})^2$

In [46]:
# Hypothesis
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

# Weight와 Bias를 0으로 초기화
# requires_grad = True : 학습할 것이라고 명시
W  = torch.zeros(1, requires_grad=True)
b  = torch.zeros(1, requires_grad=True)

# Epochs
nb_epochs = 1000

for epoch in range(nb_epochs+1) : 
    
    # H(x) 계산
    hypothesis = x_train * W + b
    
    # Cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)
    
    print('Epoch {:4d}/{} | W : {:.3f} | Cost : {:.6f}' .format(epoch, nb_epochs, W.item(), cost.item()))
    
    # Optimizer
    optimizer = torch.optim.SGD([W,b], lr=0.01)
    optimizer.zero_grad()                       # zero_grad()로 gradient 초기화
    cost.backward()                             # backward()로 gradient 계산
    optimizer.step()                            # step으로 개선

Epoch    0/1000 | W : 0.000 | Cost : 18.666666
Epoch    1/1000 | W : 0.187 | Cost : 14.770963
Epoch    2/1000 | W : 0.353 | Cost : 11.691541
Epoch    3/1000 | W : 0.500 | Cost : 9.257346
Epoch    4/1000 | W : 0.632 | Cost : 7.333169
Epoch    5/1000 | W : 0.749 | Cost : 5.812135
Epoch    6/1000 | W : 0.853 | Cost : 4.609764
Epoch    7/1000 | W : 0.945 | Cost : 3.659278
Epoch    8/1000 | W : 1.028 | Cost : 2.907896
Epoch    9/1000 | W : 1.101 | Cost : 2.313895
Epoch   10/1000 | W : 1.166 | Cost : 1.844294
Epoch   11/1000 | W : 1.224 | Cost : 1.473027
Epoch   12/1000 | W : 1.276 | Cost : 1.179487
Epoch   13/1000 | W : 1.322 | Cost : 0.947386
Epoch   14/1000 | W : 1.363 | Cost : 0.763851
Epoch   15/1000 | W : 1.400 | Cost : 0.618704
Epoch   16/1000 | W : 1.433 | Cost : 0.503902
Epoch   17/1000 | W : 1.462 | Cost : 0.413086
Epoch   18/1000 | W : 1.488 | Cost : 0.341229
Epoch   19/1000 | W : 1.511 | Cost : 0.284360
Epoch   20/1000 | W : 1.531 | Cost : 0.239337
Epoch   21/1000 | W : 1.550 | C

### Multi Variable Linear Ragression

In [47]:
# 데이터
x_train = torch.FloatTensor([[73, 80, 75],
 [93, 88, 93],
 [89, 91, 90],
 [96, 98, 100],
 [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])
# 모델 초기화
W = torch.zeros((3, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = torch.optim.SGD([W, b], lr=1e-5)

nb_epochs = 20
for epoch in range(nb_epochs + 1):
    # H(x) 계산
    hypothesis = x_train.matmul(W) + b # or .mm or @
    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)
    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    print('Epoch {:4d}/{}  |  hypothesis: {}  |  Cost: {:.6f}'\
          .format(epoch, nb_epochs, hypothesis.squeeze().detach(),cost.item()))

Epoch    0/20  |  hypothesis: tensor([0., 0., 0., 0., 0.])  |  Cost: 29661.800781
Epoch    1/20  |  hypothesis: tensor([67.2578, 80.8397, 79.6523, 86.7394, 61.6605])  |  Cost: 9298.520508
Epoch    2/20  |  hypothesis: tensor([104.9128, 126.0990, 124.2466, 135.3015,  96.1821])  |  Cost: 2915.712402
Epoch    3/20  |  hypothesis: tensor([125.9942, 151.4381, 149.2133, 162.4896, 115.5097])  |  Cost: 915.040527
Epoch    4/20  |  hypothesis: tensor([137.7967, 165.6247, 163.1911, 177.7112, 126.3307])  |  Cost: 287.936096
Epoch    5/20  |  hypothesis: tensor([144.4044, 173.5674, 171.0168, 186.2332, 132.3891])  |  Cost: 91.371071
Epoch    6/20  |  hypothesis: tensor([148.1035, 178.0143, 175.3980, 191.0042, 135.7812])  |  Cost: 29.758249
Epoch    7/20  |  hypothesis: tensor([150.1744, 180.5042, 177.8509, 193.6753, 137.6805])  |  Cost: 10.445267
Epoch    8/20  |  hypothesis: tensor([151.3336, 181.8983, 179.2240, 195.1707, 138.7440])  |  Cost: 4.391237
Epoch    9/20  |  hypothesis: tensor([151.9824

In [48]:
import torch.nn as nn
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1)
    def forward(self, x):
        return self.linear(x)

# cost 계산
cost = torch.mean((hypothesis - y_train) ** 2)

# cost 계산
import torch.nn.functional as F
cost = F.mse_loss(hypothesis, y_train)

# 데이터
x_train = torch.FloatTensor([[73, 80, 75],[93, 88, 93],[89, 91, 90],[96, 98, 100],[73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

# 모델 초기화
W = torch.zeros((3, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
model = MultivariateLinearRegressionModel()

# optimizer 설정
optimizer = torch.optim.SGD([W, b], lr=1e-5)

nb_epochs = 20
for epoch in range(nb_epochs + 1):
    
    # H(x) 계산
    hypothesis = x_train.matmul(W) + b # or .mm or @
    model = MultivariateLinearRegressionModel()

    Hypothesis = model(x_train)
    
    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)
    cost = F.mse_loss(hypothesis, y_train)
    
    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'\
          .format(epoch, nb_epochs, hypothesis.squeeze().detach(),cost.item()))

Epoch    0/20 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch    1/20 hypothesis: tensor([67.2578, 80.8397, 79.6523, 86.7394, 61.6605]) Cost: 9298.519531
Epoch    2/20 hypothesis: tensor([104.9128, 126.0990, 124.2466, 135.3015,  96.1821]) Cost: 2915.712158
Epoch    3/20 hypothesis: tensor([125.9942, 151.4381, 149.2133, 162.4896, 115.5097]) Cost: 915.040527
Epoch    4/20 hypothesis: tensor([137.7967, 165.6247, 163.1911, 177.7112, 126.3307]) Cost: 287.936096
Epoch    5/20 hypothesis: tensor([144.4044, 173.5674, 171.0168, 186.2332, 132.3891]) Cost: 91.371071
Epoch    6/20 hypothesis: tensor([148.1035, 178.0143, 175.3980, 191.0042, 135.7812]) Cost: 29.758249
Epoch    7/20 hypothesis: tensor([150.1744, 180.5042, 177.8509, 193.6753, 137.6805]) Cost: 10.445267
Epoch    8/20 hypothesis: tensor([151.3336, 181.8983, 179.2240, 195.1707, 138.7440]) Cost: 4.391237
Epoch    9/20 hypothesis: tensor([151.9824, 182.6789, 179.9928, 196.0079, 139.3396]) Cost: 2.493121
Epoch   10/20 hypo

### PyTorch Dataset

In [49]:
from torch.utils.data import Dataset

class CustomDataset(Dataset):

    def __init__(self):
        self.x_data = [[73, 80, 75],[93, 88, 93],[89, 91, 90],[96, 98, 100],[73, 66, 70]]
        self.y_data = [[152], [185], [180], [196], [142]]
    
    def __len__(self):
        return len(self.x_data)
    
    def __getitem__(self, idx):
        x = torch.FloatTensor(self.x_data[idx])
        y = torch.FloatTensor(self.y_data[idx])
        return x, y
    
dataset = CustomDataset()

In [50]:
from torch.utils.data import DataLoader

dataloader = DataLoader(dataset, batch_size=2,shuffle=True)

In [51]:
nb_epochs = 20

for epoch in range(nb_epochs + 1):
    for batch_idx, samples in enumerate(dataloader):
        
        x_train, y_train = samples
        
        # H(x) 계산
        prediction = model(x_train)
        
        # cost 계산
        cost = F.mse_loss(prediction, y_train)
        
        # cost로 H(x) 개선
        optimizer.zero_grad()
        cost.backward()
        optimizer.step()
        
        print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}'\
              .format(epoch, nb_epochs, batch_idx+1, len(dataloader),cost.item()))

Epoch    0/20 Batch 1/3 Cost: 21774.083984
Epoch    0/20 Batch 2/3 Cost: 23790.875000
Epoch    0/20 Batch 3/3 Cost: 32154.193359
Epoch    1/20 Batch 1/3 Cost: 24475.066406
Epoch    1/20 Batch 2/3 Cost: 22802.066406
Epoch    1/20 Batch 3/3 Cost: 28729.841797
Epoch    2/20 Batch 1/3 Cost: 27741.035156
Epoch    2/20 Batch 2/3 Cost: 17823.923828
Epoch    2/20 Batch 3/3 Cost: 32154.193359
Epoch    3/20 Batch 1/3 Cost: 22762.890625
Epoch    3/20 Batch 2/3 Cost: 25503.050781
Epoch    3/20 Batch 3/3 Cost: 26752.226562
Epoch    4/20 Batch 1/3 Cost: 21774.083984
Epoch    4/20 Batch 2/3 Cost: 23790.875000
Epoch    4/20 Batch 3/3 Cost: 32154.193359
Epoch    5/20 Batch 1/3 Cost: 22802.066406
Epoch    5/20 Batch 2/3 Cost: 30442.017578
Epoch    5/20 Batch 3/3 Cost: 16795.939453
Epoch    6/20 Batch 1/3 Cost: 29453.210938
Epoch    6/20 Batch 2/3 Cost: 22762.890625
Epoch    6/20 Batch 3/3 Cost: 18851.906250
Epoch    7/20 Batch 1/3 Cost: 27741.035156
Epoch    7/20 Batch 2/3 Cost: 25503.050781
Epoch    7/

### Logistic Regression

In [52]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

x_data = [[1,2], [2,3], [3,1], [4,3], [5,3], [6,2]]
y_data = [[0], [0], [0], [1], [1], [1]]

x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

print(x_train.shape)
print(y_train.shape, end='\n\n')

print('e =', torch.exp(torch.FloatTensor([1])), end='\n\n')

w = torch.zeros((2,1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

hypothesis = 1 / (1 + torch.exp(-(x_train.matmul(w) + b)))
print(hypothesis)
print(hypothesis.shape, end='\n\n')

print('1/e^{-1} =', torch.sigmoid(torch.FloatTensor([1])), end='\n\n')

hypothesis = torch.sigmoid((x_train.matmul(w) + b))
print(hypothesis)
print(hypothesis.shape)

torch.Size([6, 2])
torch.Size([6, 1])

e = tensor([2.7183])

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<MulBackward0>)
torch.Size([6, 1])

1/e^{-1} = tensor([0.7311])

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<SigmoidBackward>)
torch.Size([6, 1])


In [53]:
print(hypothesis)
print(y_train, end='\n\n')

print(-(y_train[0] * torch.log(hypothesis[0]) + (1 - y_train[0]) * torch.log(1 - hypothesis[0])), end='\n\n')

losses = -(y_train * torch.log(hypothesis) + (1 - y_train) * torch.log(1 - hypothesis))
print(losses, end='\n\n')

cost = losses.mean()
print(cost, end='\n\n')

print(F.binary_cross_entropy(hypothesis, y_train))

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<SigmoidBackward>)
tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.]])

tensor([0.6931], grad_fn=<NegBackward>)

tensor([[0.6931],
        [0.6931],
        [0.6931],
        [0.6931],
        [0.6931],
        [0.6931]], grad_fn=<NegBackward>)

tensor(0.6931, grad_fn=<MeanBackward0>)

tensor(0.6931, grad_fn=<BinaryCrossEntropyBackward>)


In [54]:
W = torch.zeros((2,1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

optimizer = optim.SGD([W,b], lr=0.01)

nb_epochs = 1000

for epoch in range(nb_epochs + 1) : 
    
    # Cost 계산
    hypothesis = torch.sigmoid(x_train.matmul(W) + b)
    cost = F.binary_cross_entropy(hypothesis, y_train)
    
    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    # epoch 100번 마다 log 출력
    if epoch % 100 == 0 : 
        print('epoch = {:4d}/{}  |  cost = {:.6f}' .format(epoch, nb_epochs, cost.item()))

print()

hypothesis = torch.sigmoid(x_train.matmul(W) + b)
print(hypothesis[:5], end='\n\n')

prediction = hypothesis >= torch.FloatTensor([0.5])
print(prediction[:5].float())
print(y_train[:5], end='\n\n')

correct_prediction = prediction.float() == y_train
print(correct_prediction[:5])

epoch =    0/1000  |  cost = 0.693147
epoch =  100/1000  |  cost = 0.578086
epoch =  200/1000  |  cost = 0.535207
epoch =  300/1000  |  cost = 0.505647
epoch =  400/1000  |  cost = 0.484024
epoch =  500/1000  |  cost = 0.467288
epoch =  600/1000  |  cost = 0.453674
epoch =  700/1000  |  cost = 0.442127
epoch =  800/1000  |  cost = 0.431998
epoch =  900/1000  |  cost = 0.422874
epoch = 1000/1000  |  cost = 0.414490

tensor([[0.2169],
        [0.2644],
        [0.6868],
        [0.6295],
        [0.7870]], grad_fn=<SliceBackward>)

tensor([[0.],
        [0.],
        [1.],
        [1.],
        [1.]])
tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.]])

tensor([[ True],
        [ True],
        [False],
        [ True],
        [ True]])


In [55]:
class BinaryClassifier(nn.Module) :
    
    def __init__(self) : 
        super().__init__()
        self.linear = nn.Linear(8,1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self, x) : 
        return self.sigmoid(self.linear(x))
    
model = BinaryClassifier()

# Opitmizer 설정
optimizer = optim.SGD(model.parameters(), lr=1)

# Epoch
nb_epochs = 100

for epoch in range(nb_epochs + 1) : 
    
    hypothesis = model(x_train)
    
    cost = F.binary_cross_entropy(hypothesis, y_train)
    
    # Cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    # 20번마다 로그 출력
    if epoch % 20 == 0 : 
        prediction = hypothesis >= torch.FloatTensor([0.5])
        correct_prediction = prediction.float() == y_train
        accuracy = correct_prediction.sum().item() / len(correct_prediction)
        print('epoch = {:4d}/{}  |  cost = {:.6f}  |  Accuracy = {:2.2f}%'\
              .format(epoch, nb_epochs, cost.item(), accuracy*100))

RuntimeError: size mismatch, m1: [6 x 2], m2: [8 x 1] at /pytorch/aten/src/TH/generic/THTensorMath.cpp:197

### Softmax Classification

In [56]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

# For reproducibility
torch.manual_seed(1)

In [57]:
z = torch.FloatTensor([1,2,3])

hypothesis = F.softmax(z, dim=0)
hypothesis

tensor([0.0900, 0.2447, 0.6652])

In [58]:
hypothesis.sum()

tensor(1.)

In [59]:
# Cross Entropy Loss
z = torch.rand(3, 5, requires_grad=True)
hypothesis = F.softmax(z, dim=1)
hypothesis

tensor([[0.2645, 0.1639, 0.1855, 0.2585, 0.1277],
        [0.2430, 0.1624, 0.2322, 0.1930, 0.1694],
        [0.2226, 0.1986, 0.2326, 0.1594, 0.1868]], grad_fn=<SoftmaxBackward>)

In [60]:
y = torch.randint(5, (3,)).long()
y

tensor([0, 2, 1])

In [61]:
y_one_hot = torch.zeros_like(hypothesis)
y_one_hot.scatter(1, y.unsqueeze(1), 1)

tensor([[1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.]])

In [62]:
cost = (y_one_hot * -torch.log(hypothesis)).sum(dim=1).mean()
cost

tensor(0., grad_fn=<MeanBackward0>)

In [63]:
# low Level
torch.log(F.softmax(z, dim=1))

tensor([[-1.3301, -1.8084, -1.6846, -1.3530, -2.0584],
        [-1.4147, -1.8174, -1.4602, -1.6450, -1.7758],
        [-1.5025, -1.6165, -1.4586, -1.8360, -1.6776]], grad_fn=<LogBackward>)

In [64]:
# High Level
F.log_softmax(z, dim=1)

tensor([[-1.3301, -1.8084, -1.6846, -1.3530, -2.0584],
        [-1.4147, -1.8174, -1.4602, -1.6450, -1.7758],
        [-1.5025, -1.6165, -1.4586, -1.8360, -1.6776]],
       grad_fn=<LogSoftmaxBackward>)

In [65]:
# Low Level
(y_one_hot * -torch.log(F.softmax(z, dim=1))).sum(dim=1).mean()

tensor(0., grad_fn=<MeanBackward0>)

In [66]:
# High Level
F.nll_loss(F.log_softmax(z, dim=1), y)

tensor(1.4689, grad_fn=<NllLossBackward>)

In [67]:
F.cross_entropy(z, y)

tensor(1.4689, grad_fn=<NllLossBackward>)

In [68]:
x_train = [[1,2,1,1],
           [2,1,3,2],
           [3,1,3,4],
           [4,1,5,5],
           [1,7,5,5],
           [1,2,5,6],
           [1,6,6,6],
           [1,7,7,7]]
y_train = [2,2,2,1,1,1,0,0]

In [69]:
x_train = torch.FloatTensor(x_train)
y_train = torch.FloatTensor(y_train)

In [70]:
# 모델 초기화
W = torch.zeros((4,3), requires_grad = True)
b = torch.zeros(1, requires_grad = True)

# Optimizer 설정
optimizer = optim.SGD([W,b], lr=0.01)

# Epoch
nb_epochs = 1000

for epoch in range(nb_epochs +1) : 
    
    # Cost 계산 (1)
    hypothesis = F.softmax(x_train.matmul(W) + b, dim=1)
    y_one_hot = torch.zeros_like(hypothesis)
    y_one_hot.scatter_(1, y.unsqueeze(1), 1)
    cost = (y_one_hot * -torch.log(hypothesis)).sum(dim=1).mean()
    
    # Cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    # epoch 100번 마다 log 출력
    if epoch % 100 == 0 : 
        print('epoch = {:4d}/{}  |  cost = {:.6f}' .format(epoch, nb_epochs, cost.item()))    

RuntimeError: Expected tensor [8, 3] and index [3, 1] to have the same size in dimension 1

In [71]:
# 모델 초기화
W = torch.zeros((4,3), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

# Optimizer 설정
optimizer = optim.SGD([W,b], lr=0.1)

# Epoch
nb_epochs = 1000

for epoch in range(nb_epochs +1) : 
    
    # Cost 계산 (2)
    z = x_train.matmul(W) + b
    cost = F.cross_entropy(z, y_train)
    
    # Cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    # epoch 100번 마다 log 출력
    if epoch % 100 == 0 : 
        print('epoch = {:4d}/{}  |  cost = {:.6f}' .format(epoch, nb_epochs, cost.item()))    

RuntimeError: Expected object of scalar type Long but got scalar type Float for argument #2 'target' in call to _thnn_nll_loss_forward

In [72]:
class SoftmaxClassifierModel(nn.Module) : 
    def __init__(self) : 
        super().__init__()
        self.linear = nn.Linear(4,3)
        
    def forward(self, x) : 
        return self.linear(x)
    
model = SoftmaxClassifierModel()

In [73]:
# Optimizer 설정
optimizer = optim.SGD(model.parameters(), lr=0.1)

# Epochs
nb_epochs = 1000

for epoch in range(nb_epochs + 1) : 
    
    # H(x) 계산
    prediction = model(x_train)
    
    # Cost 계산
    cost = F.cross_entropy(prediction, y_train)
    
    # Cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    # epoch 100번 마다 log 출력
    if epoch % 100 == 0 : 
        print('epoch = {:4d}/{}  |  cost = {:.6f}' .format(epoch, nb_epochs, cost.item()))    

RuntimeError: Expected object of scalar type Long but got scalar type Float for argument #2 'target' in call to _thnn_nll_loss_forward